pipeline {
    agent any

    stages {
        stage('Prepare') {
    steps {
        sh 'rm -rf utn-devops-app'
        sh 'git clone https://github.com/Fichen/utn-devops-app.git'
        sh 'cd utn-devops-app && git checkout unidad-2'
    }
}
        stage('Build') {
            steps {
                sh 'find . -path ./utn-devops-app/myapp/vendor -prune -o -name \\*.php -exec php -l "{}" \\;'
                retry(2) {
                    sh 'cd utn-devops-app/myapp && sudo /usr/local/bin/composer install --no-scripts --prefer-dist'
                }
            }
        }
        stage('Test') {
            steps {
                sh './utn-devops-app/myapp/vendor/bin/phpunit -c ./utn-devops-app/myapp/phpunit.xml'
            }
        }
    }
}
